<?php
App::uses('AppController', 'Controller');
/**
 * UserEmails Controller
 *
 * @property UserEmails $UserEmails
 * @property PaginatorComponent $Paginator
 */
class UserEmailsController extends AppController {

/**
 * Components
 *
 * @var array
 */
	public $components = array(
		'TimeManagement', 'Session', 'UserData', 'EmailAccess', 'RequestHandler');
	
	public $uses = array ('UserEmail');
	
	
	public function user_has_email()
	{
		$result = array('success' => 0, 'msg' => '', 'status'=>'');
		$this->layout = 'ajax';
		
		$is_ajax = $this->RequestHandler->isAjax();
		$is_post = $this->RequestHandler->isPost();
		$user_id = $this->UserData->getUserId();
		$user_email = $this->UserData->getUserEmail();
		
		if (!$is_ajax || !$is_post)
		{
			$result['msg'] = 'Bad Request';
		}
		else if (empty($user_id))
		{
			$result['msg'] = 'Please login to check confirmation status of your email.';
		}
		else
		{
			$data = $this->request->data;
			if (empty($data['email']))
			{
				$result['msg'] = 'Provide an email address to check for.';
			}
			else if ($user_email == $data['email'])
			{
				$result['status'] = 'own-confirmed';
			}
			else
			{
				$entry = $this->UserEmail->user_owns_email($data['email'], $user_id);
				
				if (!empty($entry) && !empty($entry['UserEmail']))
				{
					if (1 == $entry['UserEmail']['confirmed'])
					{
						$result['status'] = 'own-confirmed';
					}
					else
					{
						$result['status'] = 'own-no-confirmed';
					}
				}
				else
				{
					$result['status'] = 'no-own';
				}
				
			}
		}
		
		$this->set('result', $result);
	}
	
	public function add_email()
	{
		$result = array('success' => 0, 'msg' => '');
		
		$this->layout = 'ajax';
		
		$is_ajax = $this->RequestHandler->isAjax();
		$is_post = $this->RequestHandler->isPost();
		$user_id = $this->UserData->getUserId();
		$user_email = $this->UserData->getUserEmail();
		
		if (!$is_ajax || !$is_post)
		{
			$result['msg'] = 'Bad Request';
		}
		else if (empty($user_id))
		{
			$result['msg'] = 'Please login to add additional emails to your records.';
		}
		else
		{
			$data = $this->request->data;
			if (empty($data['e']))
			{
				$result['msg'] = 'Provide an email to add to your profile.';
			}
			else if ($user_email == $data['e'])
			{
				$result['msg'] = "You have already confirmed {$data['e']}.";
			}
			else
			{
				$send_confirm_email = false;
				
				$email = $data['e'];
				$entry = $this->UserEmail->user_owns_email($email, $user_id);
				
				if (!empty($entry['UserEmail']))
				{
					if (1 == $entry['UserEmail']['confirmed'])
					{
						$result['msg'] = "You have already confirmed {$email}.";
					}
					else
					{
						$confirmation_code = $entry['UserEmail']['confirmation_code'];
						$entry_id = $entry['UserEmail']['id'];
						$send_confirm_email = true;
					}
				}
				else
				{
				
					$confirmation_feed = TimeManagement::TSNowTime();
					$str_to_hash = $confirmation_feed . $email . $user_id;
					$confirmation_code = hash('ripemd160', $str_to_hash);
					$entry_id = $this->UserEmail->add_email($email, $user_id, $confirmation_code);
					$send_confirm_email = true;
				}
				
				if ($send_confirm_email)
				{
					$redir_loc = "";
					if (!empty($data['l']))
					{
						$redir_loc = urlencode($data['l']);
					}
					$confirmation_link = SITE_NAME."user_emails/confirm/{$entry_id}/{$confirmation_code}?nu={$redir_loc}";
					$email_sent = $this->EmailAccess->shoot_email_for_confirm_extra_email(
						$email, "", $confirmation_link);
					$this->set('email_sent', $email_sent);
					$result['msg'] = 'Thank you! Please check your email for a confirmation link.';
				}
			}
		}
		
		$this->set('result', $result);
		return $result;
	}
	
	public function confirm($entry_id, $confirmation_code)
	{
		$result = array('success' => 0, 'msg' => '', 'redir_url'=>'', 'auto_redir'=>false);
		$errors = false;
		
		$user_id = $this->UserData->getUserId();
		
		if (empty($user_id))
		{
			$result['msg'] = 'Please login to confirm this email address.';
			$errors = true;
		}
		
		if (!$errors)
		{
			$entry = $this->UserEmail->get_from_entry_id($entry_id);
			if (!empty($this->params->query['nu']))
			{
				$result['redir_url'] = $this->params->query['nu'];
			}
			
			if (empty($entry) || empty($entry['UserEmail']))
			{
				$result['msg'] = 'The confirmation link is either too old or is bad.';
			}
			else if ($user_id != $entry['UserEmail']['user_id'])
			{
				$result['msg'] = 'Our records show that this confirmation link was generated by a different user.';
			}
			else if (1 == $entry['UserEmail']['confirmed'])
			{
				$result['msg'] = 'You have already confirmed this email.';
				if (!empty($result['redir_url']))
				{
					$result['auto_redir'] = true;
					$result['msg'] = $result['msg'] . " If you are not redirected to next page in 60 seconds, then <a style='color:white;' href=\"{$result['redir_url']}\">click here</a>."; 
				}
			}
			else
			{
				$email = $entry['UserEmail']['email'];
				$set_email_confirmed = $this->UserEmail->set_email_confirmed($email, $user_id);
				if (empty($set_email_confirmed))
				{
					$result['msg'] = 'Unknown error while updating your record.';
				}
				else
				{
					$result['auto_redir'] = false;
					$result['msg'] = "Thanks! your email is confirmed now. <a style='color:white;' href=\"{$result['redir_url']}\">Move to the page where you were before.</a>";
				}
			}
		}
		
		$this->Session->setFlash($result['msg']);
		$this->set('result', $result);
		return $result;
	}
	
}